### ISSUE TITLE
DistriConv2dPP and other models

### ISSUE THREAD

**Issue by alivisionrd** [mit-han-lab/distrifuser#14]
Hey, so, basically Unet backbone has been replaced by SD3Transformer2DModel (Diffusion Transformers) in new stable diffusion pipeline

How can we support this?

**Comment by lmxyy** [comment]
Yeah. I think you can refer the primitives in `DistriCrossAttentionPP` and `DistriSelfAttentionPP` to support the `JointTransformerBlock` in SD3. You do not need to do anything special for the `LayerNorm` in patch parallelism, since it is normalizing the channel dimension, which is already independent across devices.

**Comment by alivisionrd** [comment]
Do you have any idea of how to  perform this action of `DistriConv2dPP` in Transformer? The hidden states in transformer do not pass through any conv layer.

**Comment by lmxyy** [comment]
I think you can directly use my implemented `DistriConv2dPP`. Nothing needs to change.

**Comment by alivisionrd** [comment]
Transformer has no conv2d layer, where should I use the `DistriConv2dPP?.`  The inputs to attention are not divided

**Comment by alivisionrd** [comment]
The transformer adds embeddings to latents before calculating attention. I wrote the code for it but it doesnt work. For example, 1,4096,1536 embeddings cannot be added to 1,2048,1536 outputs of DistriConv2dPP

**Comment by lmxyy** [comment]
Yeah, you need to slice the positional embedding. Could you share your `DistriConv2dPP` implementation? The example you showed seems to be caused by a bug. You can also run the original `Conv2d` while slicing the transformer on 4 and 8 GPUs for a sanity check to see if the issue is really caused by the convolution.

**Comment by alivisionrd** [comment]
Can you verify is your email `muyangli@mit.edu` correct?  **I will email you my code**
I will share you my custom `DistriSD3AttentionPP` and `DistriConv2dPP` code as well.

**Comment by lmxyy** [comment]
Yes. That is my email.

**Comment by alivisionrd** [comment]
Mail Sent! Check the `distrisd3attn(updated).py` script I sent

**Comment by Zctoylm0927** [comment]
Hi, I was wondering can we get a script for sd3? And now sd3.5 is released, will we support it?
